# 配置文件

package_name: com.cmcm.live
main_phone : "Android://127.0.0.1:5037/"

android_devices:
  - android_1: Android://127.0.0.1:5037/CB5A2AE8LW
  - android_2: Android://127.0.0.1:5037/T7G0216117000139
  - android_3: Android://127.0.0.1:5037/50354b4659543398-3

BasePage:
  ID_ME_PAGE: ':id/me_page'

HomePage:
  username: admin@liveme.com
  password: liveme060

SettingPage:
  ID_SETTINGS_ENTER: ':id/setting_img'
  ID_SETTINGS_LEFT: ':id/left_area'
  TEXT_FIRST_TAB: 'Account and security'
  TEXT_NETWORK_DIAGNOSIS: 'Network Diagnosis'

LoginPage:
  aaa: aaa

permission:
  - "android.permission.RECORD_AUDIO"
  - "android.permission.ACCESS_NETWORK_STATE"
  - "android.permission.ACCESS_WIFI_STATE"
  - "android.permission.INTERNET"
  - "android.permission.MODIFY_AUDIO_SETTINGS"
  - "android.permission.READ_PHONE_STATE"
  - "android.permission.BLUETOOTH"
  - "android.permission.WRITE_EXTERNAL_STORAGE"
  - "android.permission.MOUNT_UNMOUNT_FILESYSTEMS"
  - "android.permission.READ_LOGS"
  - "android.permission.CHANGE_WIFI_STATE"
  - "android.permission.MANAGE_ACCOUNTS"
  - "android.permission.GET_ACCOUNTS"
  - "android.permission.BLUETOOTH_ADMIN"
  - "android.permission.WRITE_SETTINGS"
  - "android.permission.ACCESS_FINE_LOCATION"
  - "android.permission.ACCESS_COARSE_LOCATION"
  - "android.permission.READ_EXTERNAL_STORAGE"
  - "android.permission.ACCESS_BACKGROUND_LOCATION"
  - "android.permission.ACCESS_MEDIA_LOCATION"
  - "android.permission.MODIFY_AUDIO_SETTINGS"
  - "android.permission.MANAGE_ACCOUNTS"
  - "android.permission.INTERNET"
  - "android.permission.CHANGE_WIFI_STATE"
  - "android.permission.ACCESS_NETWORK_STATE"
  - "android.permission.ACCESS_WIFI_STATE"
  - "android.permission.ACCESS_FINE_LOCATION"
  - "android.permission.READ_EXTERNAL_STORAGE"
  - "android.permission.ACCESS_COARSE_LOCATION"
  - "android.permission.READ_PHONE_STATE"
  - "android.permission.GET_ACCOUNTS"
  - "android.permission.WRITE_EXTERNAL_STORAGE"
  - "android.permission.RECORD_AUDIO"
  - "android.permission.ACCESS_BACKGROUND_LOCATION"
  - "android.permission.ACCESS_MEDIA_LOCATION"

zk_hosts: '10.61.153.83:2182'