# 配置文件

package_name: com.cmcm.live
main_phone : "Android://127.0.0.1:5037/"

android_devices:
  - android_1: Android://127.0.0.1:5037/CB5A2AE8LW
  - android_2: Android://127.0.0.1:5037/T7G0216117000139
  - android_3: Android://127.0.0.1:5037/50354b4659543398-3

BasePage:
  ID_ME_PAGE: ':id/me_page'

HomePage:
  username: admin@liveme.com
  password: liveme060
  # 顶部导航栏按钮
  ID_SEARCH: ':id/home_search_img'
  # 顶部导航总tab_id名字
  ID_HOMEPAGE_TITLE: ':id/home_tab_title'
  TEXT_MEETUP: 'Meetup'
  TEXT_FEATURED: 'Featured'
  TEXT_NEW: 'New'
  TEXT_NEARBY: 'Nearby'
  TEXT_GAME: 'Game'
  TEXT_VIDEOS: 'Videos'
  ID_HOME_RANKING_BOARD: 'com.cmcm.live:id/home_rank_img'
  # 底部导航栏按钮
  ID_LIVE_ICON: ':id/uplive'
  ID_HOME_PAGE_TAB: ':id/home_page'
  ID_FOLLOW_TAB: ':id/home_tab_follow'
  ID_MESSAGE_TAB: ':id/home_tab_message'
  ID_ME_PAGE_TAB: ':id/me_page'

SettingPage:
  ID_SETTINGS_ENTER: ':id/setting_img'
  ID_SETTINGS_LEFT: ':id/left_area'
  ID_ITEM_LOGOUT: ":id/item_logout"
  ID_BUTTON1: ":id/button1"
  TEXT_FIRST_TAB: 'Account and security'
  TEXT_NETWORK_DIAGNOSIS: 'Network Diagnosis'

LoginPage:
  ID_BOTTOM_LOGIN_LAYOUT: ':id/bottom_login_layout'
  ID_CLEAR_ID: ':id/iv_clear'
  ID_IV_CLEAR: ':id/iv_clear'
  ID_ET_EMAIL: ':id/et_email'
  ID_ET_PASSWORD: ':id/et_password'
  ID_BTNTV: ":id/btnTv"
  NAME_ANDROID_WIDGET_IMAGEVIEW: 'android.widget.ImageView'

  ID_TITLE: ":id/title"
  ID_TEXT_LOGIN: ":id/text_login"
  ID_ET_PHONE: ":id/et_phone"
  ID_LAYOUT_PHONE_ACCOUNT_PASSWORD: "id/layout_phone_account_password"
  ID_TV_COUNTRY_CODE: ":id/tv_country_code"
  TEXT_CHINA_PHONE_CODE: "86"
  TEXT_CHINA: "中国"
  TEXT_PHONE: "PHONE"

  TEXT_AGREE: 'Agree'
  TEXT_GOOGLE: 'GOOGLE'

  ID_CHECK_IN_CLOSE: ":id/check_in_close"



AnchorPage:
  ID_GAIN_BTN: "id/gain_btn"
  ID_BONUS_CLOSE_BTN: "id/bonus_close_btn"
  ID_UPLIVE: ":id/uplive"
  ID_TXT_VIDEO_START_LIVE: ":id/txt_video_start_live"
  ID_IMG_CLOSE: ":id/img_close"
  ID_BUTTON1: ":id/button1"




PrepareLivePage:
  ID_LIVE_TITLE: ':id/edt_video_title'
  ID_LIVE_COVER: ':id/edit_live_cover'
  ID_TOPIC: ':id/topic_arrow'
  ID_BEAUTY_ICON: ':id/iv_beauty'
  ID_START_LIVE: ':id/txt_video_start_live'
  ID_CLOSE: ":id/img_close"
  # multi_beam模式下元素
  ID_MULTI_AUDIO_CHOOSER: ":id/cb_nine_beam_audio"
  ID_NINE_MODE_TWO: ":id/nine_mode_two"
  ID_NINE_MODE_FOURE: ":id/nine_mode_four"
  ID_NINE_MODE_SIX: ":id/nine_mode_six"
  ID_NINE_MODE_NINE: ":id/nine_mode_nine"
  # 语音房间AUDIO
  ID_AUDIO_TAG: ":id/tag_txt"
  ID_AUDIO_CHANGE_TILTLE: ":id/audio_change_title"

LivePage:
  ID_CLOSE: ":id/img_close"
  TEXT_SWIPE_UP_GUIDE: "Swipe up to the next broadcast"
  # continue
  ID_BUTTON2: ":id/button2"
  # finish
  ID_BUTTON1: ":id/button1"
  # 主播端底部按钮
  ID_DETAIL_DATA: ":id/btn_live_detail_data"
  ID_WHISPER_MSG: ":id/btn_whisper"
  ID_MORE_ARROW_BUTTON: ":id/arrow_button"
  ID_DAILY_TASK: ":id/layout_daily_task"
  ID_MASK: ":id/layout_mask"
  ID_GAMEOUT_PK: ":id/gameout_button"
  ID_BEAM_APPLY: ":id/normal_apply_ico_bg"

permission:
  - "android.permission.RECORD_AUDIO"
  - "android.permission.ACCESS_NETWORK_STATE"
  - "android.permission.ACCESS_WIFI_STATE"
  - "android.permission.INTERNET"
  - "android.permission.MODIFY_AUDIO_SETTINGS"
  - "android.permission.READ_PHONE_STATE"
  - "android.permission.BLUETOOTH"
  - "android.permission.WRITE_EXTERNAL_STORAGE"
  - "android.permission.MOUNT_UNMOUNT_FILESYSTEMS"
  - "android.permission.READ_LOGS"
  - "android.permission.CHANGE_WIFI_STATE"
  - "android.permission.MANAGE_ACCOUNTS"
  - "android.permission.GET_ACCOUNTS"
  - "android.permission.BLUETOOTH_ADMIN"
  - "android.permission.WRITE_SETTINGS"
  - "android.permission.ACCESS_FINE_LOCATION"
  - "android.permission.ACCESS_COARSE_LOCATION"
  - "android.permission.READ_EXTERNAL_STORAGE"
  - "android.permission.ACCESS_BACKGROUND_LOCATION"
  - "android.permission.ACCESS_MEDIA_LOCATION"
  - "android.permission.MODIFY_AUDIO_SETTINGS"
  - "android.permission.MANAGE_ACCOUNTS"
  - "android.permission.INTERNET"
  - "android.permission.CHANGE_WIFI_STATE"
  - "android.permission.ACCESS_NETWORK_STATE"
  - "android.permission.ACCESS_WIFI_STATE"
  - "android.permission.ACCESS_FINE_LOCATION"
  - "android.permission.READ_EXTERNAL_STORAGE"
  - "android.permission.ACCESS_COARSE_LOCATION"
  - "android.permission.READ_PHONE_STATE"
  - "android.permission.GET_ACCOUNTS"
  - "android.permission.WRITE_EXTERNAL_STORAGE"
  - "android.permission.RECORD_AUDIO"
  - "android.permission.ACCESS_BACKGROUND_LOCATION"
  - "android.permission.ACCESS_MEDIA_LOCATION"

zk_hosts: '10.61.153.83:2182'